resync:
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/AQD.xsd
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/EnvironmentalMonitoringFacilities.xsd
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/BaseTypes.xsd
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/AreaManagementRestrictionRegulationZone.xsd
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/BaseTypes2.xsd
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/GeographicalNames.xsd
	wget -N http://dd.eionet.europa.eu/schemas/id2011850eu/ReportingUnits.xsd

