#!/bin/sh

for file in test-*
do
    echo $file ...
    expected=`echo "$file" | sed 's/^test-/expected-/'`
    xsltproc ../aqd10_rdf.xsl "$file" >result.xml
    diff "$expected" result.xml
    rm result.xml
done
